# An ansible inventory file for a small windows test range.

all:
  children:
    windows:
      hosts:
        win1:
          ansible_host: 10.0.1.2
        win2:
          ansible_host: 10.0.1.3
        win3:
          ansible_host: 10.0.1.4
    networking:
      hosts:
        core_router:
          pfsense-core: 10.0.0.1

  vars:
    ansible_ssh_user: test 

    ansible_ssh_private_key: /path/to/test
